services:
  scraping:
    build:
      context: .
      dockerfile: ./scraper/dockerfile
    volumes:
      - ${PATH_TO_DATA}:/data
    command: python /app/scraper/scrape.py --dump_path /data

  training:
    build:
      context: .
      dockerfile: ./drafter/dockerfile
    volumes:
      - ${PATH_TO_DATA}:/data
      - ${PATH_TO_EXP}:/exp
    command: python /app/drafter/train.py --data_path /data/data.json --exp_path /exp --max_iter 2000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  dev:
    build:
      context: .
      dockerfile: ./dockerfile
